// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_turnaround = "CgkIyteA-dYZEAIQDA"; // <GPGSID>
        public const string achievement_adult = "CgkIyteA-dYZEAIQEA"; // <GPGSID>
        public const string achievement_climbing_tree = "CgkIyteA-dYZEAIQAw"; // <GPGSID>
        public const string achievement_first_steps = "CgkIyteA-dYZEAIQCA"; // <GPGSID>
        public const string achievement_flowerfield = "CgkIyteA-dYZEAIQBA"; // <GPGSID>
        public const string achievement_time_to_blossom = "CgkIyteA-dYZEAIQAg"; // <GPGSID>
        public const string achievement_challenger = "CgkIyteA-dYZEAIQCg"; // <GPGSID>
        public const string achievement_blackbelt = "CgkIyteA-dYZEAIQCw"; // <GPGSID>
        public const string achievement_planting_the_seed = "CgkIyteA-dYZEAIQAA"; // <GPGSID>
        public const string achievement_growing_stem = "CgkIyteA-dYZEAIQAQ"; // <GPGSID>
        public const string achievement_amateur = "CgkIyteA-dYZEAIQCQ"; // <GPGSID>
        public const string achievement_cherry_blossom_blues = "CgkIyteA-dYZEAIQBg"; // <GPGSID>
        public const string achievement_child = "CgkIyteA-dYZEAIQDw"; // <GPGSID>
        public const string achievement_rainforest_dryer = "CgkIyteA-dYZEAIQBQ"; // <GPGSID>
        public const string achievement_turning_tables = "CgkIyteA-dYZEAIQDQ"; // <GPGSID>
        public const string achievement_forest_of_mountains = "CgkIyteA-dYZEAIQBw"; // <GPGSID>
        public const string achievement_veteran = "CgkIyteA-dYZEAIQEQ"; // <GPGSID>
        public const string achievement_flippin_ninja = "CgkIyteA-dYZEAIQDg"; // <GPGSID>

}

